# Generated by Django 4.1.1 on 2022-09-27 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('079da681-862c-48f0-a6c9-eab4308c95c3'), editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
