# Generated by Django 4.1.1 on 2022-09-29 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_user_first_name_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d06926db-b441-4386-96b0-84a007a23f19'), editable=False, primary_key=True, serialize=False),
        ),
    ]
