# Generated by Django 4.1.1 on 2022-09-29 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ef4b5fb-9a6c-426d-8cba-abb69f437b88'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1aabad62-18a3-4525-8fe8-7d794a164759'), editable=False, primary_key=True, serialize=False)),
                ('nama_resto', models.CharField(max_length=100)),
                ('tanggal_tagihan', models.DateField()),
                ('subtotal', models.IntegerField()),
                ('pajak', models.IntegerField()),
                ('biaya_layanan', models.IntegerField()),
                ('biaya_lainnya', models.IntegerField()),
                ('diskon', models.IntegerField()),
                ('jumlah_total', models.IntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('changed_dt', models.DateTimeField(auto_now=True)),
                ('pic_tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('595006b6-04b4-4e58-9ee9-b82bf0a8af11'), editable=False, primary_key=True, serialize=False)),
                ('nama_pesanan', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.tagihan')),
            ],
        ),
        migrations.CreateModel(
            name='Pemesan',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1aa2d0ba-382c-49be-bcc7-62ede02c1b4a'), editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('pemesan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.pesanan')),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.tagihan')),
            ],
        ),
    ]
